# ---------- environment ----------
env: dev # Jawne srodowisko

# ---------- raw file paths ----------
paths:
  raw_csv: /Volumes/workspace/bronze/raw/           
  raw_macro: /Volumes/workspace/bronze/raw/macro/

# ---------- filenames ----------
files:
  qqq_entities: qqq-etf-constituents.csv

# ---------- tables ----------
tables:
  bronze_qqq: bronze.qqq_etf_constituents
  bronze_qqq_categories: bronze.qqq_etf_categories
  bronze_fred_macro_indicators: bronze.fred_indicators
  bronze_fred_macro_indicator_metadata: bronze.fred_macro_metadata_indicators
  #bronze_qqq_enriched: bronze.qqq_etf_entities_enriched #?
  bronze_ohlcv: bronze.ohlcv_indicators
  silver_qqq: silver.qqq_entities
  silver_qqq_categoties: silver.qqq_etf_categories
  silver_macro_indicators: silver.fred_indicators
  silver_macro_indicator_metadata: silver.fred_macro_metadata_indicators
  silver_ohlcv: silver.ohlcv_indicators

# ---------- fred ----------
fred:
  base_url: https://api.stlouisfed.org/fred
  series_ids:
    - CPIAUCSL
    - CPILFESL
    - FEDFUNDS
    - DGS10
    - DGS2
    - UNRATE
    - INDPRO
    - T10YIE
  rate_limit_per_second: 2
  window_refresh_months: 12

# ---------- yfinance ----------
yfinance:
  start_date: 2010-01-01
  window_refresh_months: 12
